### ISSUE TITLE
A few bugs on latest beta

### ISSUE THREAD

**Issue by AuroraWright** [roxgib/anki-contanki#27] opened 2022-10-23 14:27 UTC
- Custom actions on latest Anki and macOS aren't triggering at all when tied to a button, I tried setting several of them but no dice, the button works again as soon as you switch to a non-custom action. Previous beta works fine
- Contanki crashes if there's any .DS_Store file in the user_files folder (this had me confused for a while), interestingly it's not happening on the previous version.

**Comment by Lou-Rye** [comment] 2022-10-23 15:20
I am having similar issues as well; it just doesn't even work for me anymore

**Comment by roxgib** [comment] 2022-10-23 21:26
Thanks @AuroraWright

The issue with custom actions has been addressed with [cb778e4](https://github.com/roxgib/anki-contanki/commit/cb778e4061d11023c890beec472a2c49fb0b3ea3) (turns out I when I tested whether it works I reused the name of an existing action, and got tricked into thinking they worked. Pretty silly of me!)

I'll get into the second issue later today, I'm surprised I didn't encounter it myself but it should be trivial to fix.

**Comment by roxgib** [comment] 2022-10-24 07:47
@AuroraWright can you post the error message of the .DS_Store crash? I'm not able to reproduce it.

**Comment by AuroraWright** [comment] 2022-10-24 14:18
@roxgib sorry, apparently it's the "profiles" subfolder and not user_files itself.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/15571693/197548100-832cffa5-54e6-44dc-85eb-c315fb46b602.png">
I guess it's trying to parse it as a profile

**Comment by AuroraWright** [comment] 2022-10-24 14:19
Also thanks for the quick fix, custom actions work again now

**Comment by roxgib** [comment] 2022-10-30 09:47
The .DS_Store is was fixed with [65aac35](https://github.com/roxgib/anki-contanki/commit/65aac357815e822e6f3dc84bfd203cecbd57fc75)

**Closed by roxgib** 2022-10-30 09:47 UTC
