### ISSUE TITLE
Nintendo Switch Controller "Couldn't Find Profile 'Wireless Gamepad (Vendor:0000 Product:0000)' 

### ISSUE THREAD

**Issue by paggarwal24** [roxgib/anki-contanki#19] opened 2022-08-22 21:58 UTC
Hi, I'm running Anki on Windows and had this error message: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-22 17:45:25

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 122, in on_receive_message
    funcs[func](*args)
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 63, in on_connect
    self.mods = [False] * len(self.profile.mods)
AttributeError: 'NoneType' object has no attribute 'mods'

**Comment by roxgib** [comment] 2022-08-31 23:13
Apologies, this was caused by some changes made to prevent another error with profile names. It will be fixed in the next beta.

**Closed** 2022-10-30 10:16 UTC
Labels: Beta 8
