### ISSUE TITLE
Controller options for Dialog not working

### ISSUE THREAD

**Issue by Nikki5210** [roxgib/anki-contanki#81] opened 2024-01-21 18:25 UTC
When trying to change key mapping for "X" key to "enter" in the dialog options, it is not working. Tried it use it in the Set due date dialog page, the Enter did not work.

**Comment by roxgib** [comment] 2024-01-24 03:54
Interaction with dialogs is still hit and miss due to #1, which I haven't found the time to work on in a while. I'm closing this as a duplicate of that issue, but I do still plan to keep working on it , hopefully within the next few months.

**Closed by roxgib** 2024-01-24 03:54 UTC
