### ISSUE TITLE
8bit zero 2 anki on ASUS

### ISSUE THREAD

**Issue by mjd914** [roxgib/anki-contanki#10] opened 2022-07-20 05:38 UTC
Hi there, new to this and following a thread of contanki add-on issues but couldn't resolve my issue. I had been using my remote for about a month and came across an error message to disable all my add-ons and figure out what is causing the problem. Contanki is the only one it could be. This had happened once before but everything kept working after I closed the error box. My error message is below:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-20 01:06:17

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 46, in on_connect
    self.profile = findProfile(controller, self.len_buttons, self.len_axes)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1898790263\profile.py", line 378, in findProfile
    copyProfile(profile_to_copy, controller)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1898790263\profile.py", line 360, in copyProfile
    profile.save()
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1898790263\profile.py", line 172, in save
    with open(path, 'w') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\AppData\\Roaming\\Anki2\\addons21\\1898790263\\user_files\\profiles\\8BitDo Zero 2 gamepad (Vendor: 2dc8 Product: 9018)'

Also, it would show that I had 3 different controllers connected when I only had one. Not sure why this is going on and hopefully it can be resolved. I don't know anything about the way this works.

**Comment by roxgib** [comment] 2022-07-21 23:28
Hey, looks like it wasn't able to detect the controller successfully. I'm still getting that figured out for some controllers. I've added this controller ID to the list, and updated the fallback controller detection code to better handle 8BitDo controllers, though unfortunately they'd don't always report themselves accurately. 

I believe the specific error you've seen is caused by the profile name containing invalid characters, so I've also added some sanitisation to the profile names to avoid that in the future. By default it uses the controller name as the profile name, but in this case because it couldn't detect that it fell through to using the device ID name which contained a colon.

I'm hoping to push out a new update later this week which will contain these fixes. In the meantime, would you give [this version](https://github.com/roxgib/anki-contanki/files/9163360/contanki.ankiaddon.zip) a try to confirm that the issue is fixed?

Thanks for the report!

**Comment by roxgib** [comment] 2022-08-02 02:19
This should be fixed with Beta 6, which has now been published to AnkiWeb. If not, let me know and I'll reopen the issue. Thanks for the report!

**Comment by mjd914** [comment] 2022-08-08 17:26
Hi there, I tried out the updated version but continue to get an issue. 
First, this pops up:
Couldn't find profile 'Bluetooth Wireless Controller    (Vendor: 2dc8 Product: 3230)'
Then this:
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.Debug info:Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5Platform: Windows 10Flags: frz=True ao=True sv=2Add-ons, last update check: 2022-08-08 13:08:35
Caught exception:Traceback (most recent call last):  File "aqt.webview", line 42, in cmd  File "aqt.webview", line 149, in _onCmd  File "aqt.webview", line 618, in _onBridgeCmd  File "aqt.hooks_gen", line 4358, in __call__  File "C:\Users\jesus\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 122, in on_receive_message    funcs[func](*args)  File "C:\Users\jesus\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 63, in on_connect    self.mods = [False] * len(self.profile.mods)AttributeError: 'NoneType' object has no attribute 'mods'

Thank you for your help!


    On Monday, August 1, 2022 at 10:19:31 PM EDT, Sam Bradshaw ***@***.***> wrote:  
 
 


This should be fixed with Beta 6, which has now been published to AnkiWeb. If not, let me know and I'll reopen the issue. Thanks for the report!

**Comment by roxgib** [comment] 2022-08-12 01:52
Thanks for letting me know. The issue where it will throw an error if it can't find the profile will be fixed in the next beta ([85c5008](https://github.com/roxgib/anki-contanki/commit/85c500828468da0eaad7c6b82f0e048c86647320)). You might have to open up the config and select your original profile if you've made changes to it that you want to keep since it will load the default profile if it can't find the saved one. This should only be required once.

I'll leave this open until the next beta is released, which should be either today or tomorrow.

**Closed** 2022-10-14 05:37 UTC
Labels: Beta 6, Beta 8
