### ISSUE TITLE
Linux QPainter Error

### ISSUE THREAD

**Issue by yash-fn** [roxgib/anki-contanki#9] opened 2022-07-12 14:26 UTC
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-11 20:04:16
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/home/user/.local/share/Anki2/addons21/1898790263/contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "/home/user/.local/share/Anki2/addons21/1898790263/contanki.py", line 57, in on_connect
    self.controlsOverlay = ControlsOverlay(
  File "/home/user/.local/share/Anki2/addons21/1898790263/overlay.py", line 31, in __init__
    self.controls = {
  File "/home/user/.local/share/Anki2/addons21/1898790263/overlay.py", line 32, in <dictcomp>
    control: ControlButton(button, self.profile.controller, on_left=False, is_large=is_large)
  File "/home/user/.local/share/Anki2/addons21/1898790263/components.py", line 17, in __init__
    self.pixmap = get_button_icon(controller, button)
  File "/home/user/.local/share/Anki2/addons21/1898790263/funcs.py", line 86, in get_button_icon
    with QPainter(pixmap) as painter:
ValueError: QPainter must be created with a device
```

**Comment by yash-fn** [comment] 2022-07-12 14:51
using 8bitdo zero 2 controller in dual shock 3 (xinput) mode causes this output. Using dinput mode however and it works. platofrm linux. should I close as this is expected behavior or should xinput also work?

**Comment by yash-fn** [comment] 2022-07-12 15:26
I take that back. All the buttons are messed up. using 8bitdo zero profile x is y, y is L, B is b, A is a, l is select, and R is start. the start and select buttons are totally non-responsive. again this is with dinput mode since xinput mode just crashes plugin.

**Comment by yash-fn** [comment] 2022-07-13 02:58
Okay so within button.py I had to change the keymap to the following to get it all to work correctly:

```python
    "8BitDo Zero": {
        0: 'A',
        1: 'B',
        3: 'X',
        4: 'Y',
        6: 'Left Shoulder',
        7: 'Right Shoulder',
        10: 'Select',
        11: 'Start',
        100: 'D-Pad Left',
        101: 'D-Pad Right',
        102: 'D-Pad Up',
        103: 'D-Pad Down',
    },
```

**Comment by yash-fn** [comment] 2022-07-13 02:59
Basically with dinput mode on the zero2, there is no button 2 or 5 and and select and start are 10 and 11. The other get rearranged variously too.

**Comment by roxgib** [comment] 2022-07-13 03:05
Thanks for the report. I hadn't realised that the button layouts would be different in different modes (or perhaps it's wrong on all modes and no one had told me?). I've added a separate entry for "8BitDo Zero (Direct Input Mode)". If I've interpreted your last comment correctly that should contain the correct button assignments, and hopefully make Select and Start functional again. 
https://github.com/roxgib/anki-contanki/blob/229d9523c4be4ff5cb28a5f2ea13128d2369ede6/contanki/buttons.py#L335-L362

**Comment by roxgib** [comment] 2022-07-13 03:07
Oops, just saw your latest comments. I had guessed 8 & 9 for Select and Start, but if it's actually 10 & 11 I'll update that again to reflect it.

**Comment by roxgib** [comment] 2022-07-13 03:17
As for the error when using xinput mode, I'm not sure what's causing that (the specific error is caused when it can't find the button icon it needs, but that shouldn't happen here). I've added some code to provide a more useful error message. Would try the attached version and let me know:
- Does the Dinput mode work for you? You'll need to select the "8BitDo Zero (Direct Input Mode)" config controls screen
- What error message do you now get when using xinput mode?
[contanki.ankiaddon.zip](https://github.com/roxgib/anki-contanki/files/9098633/contanki.ankiaddon.zip)

**Comment by yash-fn** [comment] 2022-07-13 16:01
Sure thing. I'll give it a go today or tomorrow.

**Comment by yash-fn** [comment] 2022-07-14 02:50
So, weird stuff:

- Disabled original add-on. Installed from file the add-on you linked.
- Set up by entering controller options (controller in dinput mode) and changing to "8BitDo Zero (Direct Input Mode)". Tested each button and everything was mapped perfectly. Main/first page in controller options didn't update correctly as it still showed axes/modifier options for a dual shock 4 controller, but went ahead and clicked save.
- Everything works as expected with controller set to default options for each button. 
- Attempted to modify buttons to custom preferences by re-entering controller options. This resulted in following error preventing me from even entering options page:
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-13 21:31:26
Add-ons possibly involved: ⁨Contanki - Controller Support⁩

Caught exception:
Traceback (most recent call last):
  File "/home/USER/.local/share/Anki2/addons21/contanki/contanki.py", line 170, in on_config
    ContankiConfig(focus, self.profile)
  File "/home/USER/.local/share/Anki2/addons21/contanki/config.py", line 33, in __init__
    self.setup_options()
  File "/home/USER/.local/share/Anki2/addons21/contanki/config.py", line 318, in setup_options
    for axis, name in AXES_NAMES[self.profile.controller].items():
KeyError: '8BitDo Zero (Direct Input Mode)'
```
This seems related to how the first page of options didn't update correctly and was still showing 4 axes and more modifier options than the 8bitdo had. Not sure. But ignoring fact that I can't re-enter options to customize anything, the buttons were mapped perfect for dinput mode.

Now for xinput mode:
Immediately upon controller connecting to computer with xinput mode I get the following error from add-on:
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-13 21:31:26
Add-ons possibly involved: ⁨Contanki - Controller Support⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/home/USER/.local/share/Anki2/addons21/contanki/contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "/home/USER.local/share/Anki2/addons21/contanki/contanki.py", line 57, in on_connect
    self.controlsOverlay = ControlsOverlay(
  File "/home/USER/.local/share/Anki2/addons21/contanki/overlay.py", line 31, in __init__
    self.controls = {
  File "/home/USER/.local/share/Anki2/addons21/contanki/overlay.py", line 32, in <dictcomp>
    control: ControlButton(button, self.profile.controller, on_left=False, is_large=is_large)
  File "/home/USER/.local/share/Anki2/addons21/contanki/components.py", line 17, in __init__
    self.pixmap = get_button_icon(controller, button)
  File "/home/USER/.local/share/Anki2/addons21/contanki/funcs.py", line 86, in get_button_icon
    raise FileNotFoundError(f"Button {button} for controller {controller} not found")
FileNotFoundError: Button  for controller DualShock 3 not found

```

If I, however, just modify the map for the regular 8bitdo profile to match that of the new dinput one you created, then everything works perfectly fine with basically no errors whatsoever.

**Comment by roxgib** [comment] 2022-07-14 05:35
> Main/first page in controller options didn't update correctly as it still showed axes/modifier options for a dual shock 4 controller

Yep, you have to go through saving and reopening the config dialog before those update. On my list to fix during a future refactor of the config code. 

> Attempted to modify buttons to custom preferences by re-entering controller options. This resulted in following error preventing me from even entering options page

My bad, I've added the axes so that should work now. 

As for the original xinput issue, I've now managed to reproduce it on my end. Turned out the folder of button icons that should have been called "DualShock 3" was actually called "Dualshock 3" (with a lower case 's') so when your controller was emulating a DualShock 3 it wouldn't work (and, as it turns out, the same issue would have occurred for any Linux user with an actual DualShock 3). 

Anyway, [this version](https://github.com/roxgib/anki-contanki/files/9108736/contanki.ankiaddon.zip) should now work if you wouldn't mind giving it a try. Do let me know if the controls map correctly for both modes - it's possible the original mapping was wrong as well. It's also possible there's a difference in mappings between platforms, so I'll need to do some more testing before releasing it.

**Comment by yash-fn** [comment] 2022-07-15 02:49
Dinput mode works perfectly now as far as I can tell. Minor Exception: I have to set modifier keys to Select and Start in order for them to actually be L and R. So perhaps the wrong button is being displayed? If I attempt to change this to anything else, the modifier keys change into all sort of random variations. But as long as I don't touch it, all works perfect.

![image](https://user-images.githubusercontent.com/76577754/179137205-277bc8f2-db5c-498a-b24f-69068e9a2627.png)
![image](https://user-images.githubusercontent.com/76577754/179137255-270300ea-30d6-49b0-b4bd-eee4d4469aee.png)


Xinput Mappings are wrong but I have discovered the correct ones now that xinput mode doesn't crash anymore:

```python
    "8BitDo Zero for Xinput Mode": {
        1: 'A',
        0: 'B',
        3: 'X',
        2: 'Y',
        4: 'Left Shoulder',
        5: 'Right Shoulder',
        6: 'Select',
        7: 'Start',
        100: 'D-Pad Left',
        101: 'D-Pad Right',
        102: 'D-Pad Up',
        103: 'D-Pad Down',
    },
```

**Comment by yash-fn** [comment] 2022-07-15 02:54
Also, I should mention that this 8bitdo has multiple modes with Dinput and Xinput being the most likely used for windows, linux, and android users. MacOS users and iOS users will likely gravitate towards the 8bitdo's macos mode, which I can't test on linux. Apparently X/Dinput will not work on a Mac as Apple rejects it? This might mean you'd have to support yet another mode for MacOS and have to ask a mac user for details. It also has a nintendo switch mode, but as Anki doesn't exists for switch you can probably skip support for that mode.

**Comment by yash-fn** [comment] 2022-07-22 19:38
Should I close this issue or do you wish to leave it open?

**Comment by x51mon** [comment] 2022-07-23 08:35
I get the following errors with a Dualshock 3 controller.

Version from the Add-On page:

```python
Debuginformationen:
Anki 2.1.54 (88e539aa) Python 3.10.5 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-07-22 16:04:53
Möglicherweise beteiligte Erweiterungen: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 42, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 149, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 618, in _onBridgeCmd
    handled, result = gui_hooks.webview_did_receive_js_message(
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 4358, in __call__
    handled = filter(handled, message, context)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 57, in on_connect
    self.controlsOverlay = ControlsOverlay(
  File "/home/simon/.local/share/Anki2/addons21/1898790263/overlay.py", line 31, in __init__
    self.controls = {
  File "/home/simon/.local/share/Anki2/addons21/1898790263/overlay.py", line 32, in <dictcomp>
    control: ControlButton(button, self.profile.controller, on_left=False, is_large=is_large)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/components.py", line 17, in __init__
    self.pixmap = get_button_icon(controller, button)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/funcs.py", line 86, in get_button_icon
    with QPainter(pixmap) as painter:
ValueError: QPainter must be created with a device
```




And with the most recent version from GitHub:

```python
Debuginformationen:
Anki 2.1.54 (88e539aa) Python 3.10.5 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-07-22 16:04:53
Möglicherweise beteiligte Erweiterungen: ⁨contanki_git⁩

Caught exception:
Traceback (most recent call last):
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/funcs.py", line 132, in get_button_icon
    with QPainter(pixmap) as painter:
ValueError: QPainter must be created with a device

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 42, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 149, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 618, in _onBridgeCmd
    handled, result = gui_hooks.webview_did_receive_js_message(
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 4358, in __call__
    handled = filter(handled, message, context)
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/contanki.py", line 57, in on_connect
    self.controlsOverlay = ControlsOverlay(
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/overlay.py", line 31, in __init__
    self.controls = {
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/overlay.py", line 32, in <dictcomp>
    control: ControlButton(button, self.profile.controller, on_left=False, is_large=is_large)
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/components.py", line 18, in __init__
    self.pixmap_glow = get_button_icon(controller, button, glow=True)
  File "/home/simon/.local/share/Anki2/addons21/contanki_git/funcs.py", line 135, in get_button_icon
    raise FileNotFoundError(
FileNotFoundError: Button Cross for controller DualShock 3 not found
```

**Comment by roxgib** [comment] 2022-07-27 03:09
Thanks. I think I might actually need to rewrite this function with a fallback option if it can't find the correct icon, as well as write some tests that ensure the icons can be generated for all supported controllers. I'm going to do that tonight, it'll probably be helpful in the future when add new controllers.

**Comment by roxgib** [comment] 2022-07-31 02:31
I've just published Beta 6 [here](https://github.com/roxgib/anki-contanki/releases/tag/v0.7.0-beta). It'd be great if you could give it a go and let me know if this issue is resolved - I've rewritten the relevant function to generate a text icon if loading of the icon fails, so while it should also now load all the icons correctly there's a fallback if it doesn't.

**Comment by roxgib** [comment] 2022-07-31 02:49
> And with the most recent version from GitHub...

It turns out that git wasn't recognising the case change, so while I'd fixed the issue locally and in the package I'd uploaded here it wasn't reflected in the repo. I've now fixed that as well, so they should behave the same.

**Comment by x51mon** [comment] 2022-08-01 12:41
> I've just published Beta 6 [here](https://github.com/roxgib/anki-contanki/releases/tag/v0.7.0-beta).

Yes, it works perfectly now. Thank you for resolving this quickly.

**Comment by roxgib** [comment] 2022-08-02 00:19
Great, thanks for helping me to chase it down!

**Closed by roxgib** 2022-08-02 00:19 UTC
Labels: Beta 6
